name: Deploy on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - staging

permissions:
  contents: read

jobs:
  deploy-production:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        run: |
          curl --request POST \
            --url "${{ secrets.RENDER_DEPLOY_HOOK_URL_PROD }}" \
            --header 'content-type: application/json'

  deploy-staging:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'staging'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        run: |
          curl --request POST \
            --url "${{ secrets.RENDER_DEPLOY_HOOK_URL_STAGING }}" \
            --header 'content-type: application/json'
